/*
The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones.
It starts with 0 and 1, and subsequent numbers are generated by adding the last two numbers in the sequence.*/

function fibonacciSequence(n) {
    var sequence = [0, 1]; // Initial Fibonacci sequence with the first two numbers

    for (var i = 2; i <= n; i++) {
        sequence[i] = sequence[i - 1] + sequence[i - 2];
    }

    return sequence.slice(0, n + 1);
}

function main() {
    var n = 15; // Generate Fibonacci sequence up to the 10th number
    var fibonacciSeq = fibonacciSequence(n);
    console.log(fibonacciSeq);
}
main();

//alternative way 
function fibonacciSequence(n) {
    var sequence = [0, 1]; // Initial Fibonacci sequence with the first two numbers

    if (n === 0) {
        return [0]; // Special case for n = 0
    } else if (n === 1) {
        return sequence; // Special case for n = 1
    } else {
        // Generate the Fibonacci sequence up to n
        for (var i = 2; i <= n; i++) {
            var nextNum = sequence[i - 1] + sequence[i - 2];
            sequence.push(nextNum);
        }

        return sequence;
    }
}

function main() {
    var n = 15; // Generate Fibonacci sequence up to the 10th number
    var fibonacciSeq = fibonacciSequence(n);
    console.log(fibonacciSeq);
}
main();